services:
  urlshortener.api:
    image: ${DOCKER_REGISTRY-}urlshortenerapi
    container_name: UrlShortener.Api
    build:
      context: .
      dockerfile: src/UrlShortener.Api/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - euromotors.db
  euromotors.db:
    image: postgres:17
    container_name: UrlShortener.Db
    restart: always
    environment:
      - POSTGRES_DB=urlshortener
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

